-- AlterTable
ALTER TABLE "DriverStatus" ADD COLUMN     "heading" DOUBLE PRECISION,
ADD COLUMN     "lat" DOUBLE PRECISION,
ADD COLUMN     "lng" DOUBLE PRECISION,
ADD COLUMN     "speed" DOUBLE PRECISION;
